packages:
  - packages/*
  - config/*
  - examples/*

ignoredBuiltDependencies:
  - esbuild

catalogs:
  build:
    vite: ^7.2.2
    typescript: ^5.9.3
    tsdown: ^0.15.12
  format:
    "@ianvs/prettier-plugin-sort-imports": ^4.7.0
    prettier-plugin-packagejson: ^2.5.19
    prettier: ^3.6.2
  lint:
    "@eslint/js": ^9.39.1
    "@eslint/eslintrc": ^3.3.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react: ^7.37.5
    eslint: ^9.39.1
    typescript-eslint: ^8.46.3
    jiti: ^2.6.1
  test:
    vitest: ^4.0.8
    "@vitest/browser": ^4.0.8
    "@playwright/test": ^1.56.1
  types:
    "@types/node": ^22.19.0
  script:
    "taze": "^19.9.0"
    "@maz-ui/changelogen-monorepo": "^4.3.0"
