packages:
  - packages/*
  - config/*
  - examples/*

catalogs:
  build:
    tsdown: ^0.15.12
    typescript: ^5.9.3
    vite: ^7.2.2
  format:
    '@ianvs/prettier-plugin-sort-imports': ^4.7.0
    prettier: ^3.6.2
    prettier-plugin-packagejson: ^2.5.19
  lint:
    '@eslint/eslintrc': ^3.3.1
    '@eslint/js': ^9.39.1
    eslint: ^9.39.1
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    jiti: ^2.6.1
    typescript-eslint: ^8.46.3
  react:
    '@types/react': ^19.2.4
    '@types/react-dom': ^19.2.3
    react: ^19.2.0
    react-dom: ^19.2.0
  script:
    relizy: ^0.2.6-beta.1
    taze: ^19.9.0
  test:
    '@playwright/test': ^1.56.1
    '@vitejs/plugin-react': ^5.1.1
    '@vitest/browser': ^4.0.8
    '@vitest/browser-playwright': ^4.0.8
    vitest: 4.0.8
  types:
    '@types/node': ^22.19.0

ignoredBuiltDependencies:
  - esbuild
  - relizy
